# Generated by Django 4.1.7 on 2024-03-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flight_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='frequency',
            field=models.CharField(default='daily', max_length=15),
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='basic_cost',
            field=models.IntegerField(default=3500),
        ),
    ]
